# Use the official PostgreSQL image from Docker Hub
FROM postgres:latest

# Set environment variables
ENV POSTGRES_DB db_agency
ENV POSTGRES_USER user_agency
ENV POSTGRES_PASSWORD password_agency

# Expose the default PostgreSQL port (5432)
EXPOSE 5432